### ISSUE TITLE
dead link for December 2022

### ISSUE THREAD

**Issue by stelios-c** [astrojuanlu/juanluisback-twitter-archive#1]
Hello @astrojuanlu ,

https://twitter.archive.juanlu.space/ has a December 2022 link to ```2022/2022-12-01-tweets.html``` which gives 404 error, no such file in the repository (or on the webserver).

Happy holidays!

**Comment by astrojuanlu** [comment]
Hi Stelios, thanks a lot! Good catch, I didn't tweet in December 😅 will remove it
